"""
Alerting dispatcher.

Sends watchdog alerts through Airflow's native channels:
- Airflow task logs (always)
- Email via ``airflow.utils.email.send_email`` (if configured)
- Slack webhook (if configured)

No external dependencies — uses only what Airflow already provides.
"""

from __future__ import annotations

import json
import logging
from urllib.request import Request, urlopen

from airflow_watchdog.config import WatchdogConfig
from airflow_watchdog.detectors import Alert, Severity

logger = logging.getLogger(__name__)


def dispatch(alerts: list[Alert], config: WatchdogConfig) -> None:
    """Send alerts through all configured channels."""
    if not alerts:
        logger.info("Watchdog: no alerts to dispatch.")
        return

    # Always log
    _log_alerts(alerts)

    # Email
    if config.alert_emails:
        _send_email(alerts, config)

    # Slack
    if config.alert_slack_webhook:
        _send_slack(alerts, config)


def _log_alerts(alerts: list[Alert]) -> None:
    """Write alerts to the Airflow task log."""
    critical = [a for a in alerts if a.severity == Severity.CRITICAL]
    warnings = [a for a in alerts if a.severity == Severity.WARNING]

    logger.warning(
        "Watchdog found %d alert(s): %d critical, %d warning",
        len(alerts),
        len(critical),
        len(warnings),
    )
    for alert in alerts:
        log_fn = logger.critical if alert.severity == Severity.CRITICAL else logger.warning
        log_fn(str(alert))


def _send_email(alerts: list[Alert], config: WatchdogConfig) -> None:
    """Send alert summary via Airflow's email utility."""
    try:
        from airflow.utils.email import send_email
    except ImportError:
        logger.warning("Cannot import airflow.utils.email; skipping email alerts.")
        return

    critical = [a for a in alerts if a.severity == Severity.CRITICAL]
    warnings = [a for a in alerts if a.severity == Severity.WARNING]

    subject = (
        f"[Watchdog] {len(alerts)} alert(s): {len(critical)} critical, {len(warnings)} warning"
    )

    rows = []
    for a in sorted(alerts, key=lambda x: (x.severity.value, x.dag_id)):
        badge = "🔴" if a.severity == Severity.CRITICAL else "🟡"
        target = f"{a.dag_id}.{a.task_id}" if a.task_id else a.dag_id
        rows.append(
            f"<tr><td>{badge}</td><td>{a.alert_type.value}</td><td>{target}</td><td>{a.message}</td></tr>"
        )

    html = f"""\
    <h3>Watchdog Alerts</h3>
    <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;">
        <tr><th></th><th>Type</th><th>DAG / Task</th><th>Details</th></tr>
        {"".join(rows)}
    </table>
    <p style="color: #888; font-size: 0.9em;">
        Generated by airflow-provider-watchdog.
        Configure thresholds via Airflow Variable <code>watchdog_config</code>.
    </p>
    """

    try:
        send_email(to=config.alert_emails, subject=subject, html_content=html)
        logger.info("Watchdog email sent to %s", config.alert_emails)
    except Exception:
        logger.exception("Failed to send watchdog email")


def _send_slack(alerts: list[Alert], config: WatchdogConfig) -> None:
    """Post alert summary to a Slack webhook."""
    critical = [a for a in alerts if a.severity == Severity.CRITICAL]

    lines = [f"*Watchdog*: {len(alerts)} alert(s) ({len(critical)} critical)"]
    for a in alerts[:20]:  # cap to avoid huge messages
        icon = "🔴" if a.severity == Severity.CRITICAL else "🟡"
        target = f"`{a.dag_id}.{a.task_id}`" if a.task_id else f"`{a.dag_id}`"
        lines.append(f"{icon} *{a.alert_type.value}* {target}: {a.message}")

    if len(alerts) > 20:
        lines.append(f"_…and {len(alerts) - 20} more_")

    payload = json.dumps({"text": "\n".join(lines)}).encode()

    try:
        req = Request(
            config.alert_slack_webhook,  # type: ignore[arg-type]
            data=payload,
            headers={"Content-Type": "application/json"},
        )
        urlopen(req, timeout=10)  # noqa: S310
        logger.info("Watchdog Slack notification sent")
    except Exception:
        logger.exception("Failed to send watchdog Slack notification")
